# References:
# 1. https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
# 2. https://circleci.com/docs/2.0/building-docker-images/
#

version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.06.1-ce
        environment:
          BMO_IMAGE_NAME: mozillabteam/bmo
    steps:
      - setup_remote_docker
      - run:
          name: install git and ssh
          command: apk update && apk add git openssh-client
      - checkout
      - run:
          name: build container
          command: docker build -t $BMO_IMAGE_NAME:$CIRCLE_BRANCH .
      - run:
          name: run sanity tests
          command: |
            docker run \
              --env-file=docker_files/tests.env \
              $BMO_IMAGE_NAME:$CIRCLE_BRANCH prove t
      - run:
          name: create bmo network for tests
          command: docker network create bmo_net
      - run:
          name: create /data volume for tests
          command: docker volume create bmo_data
      - run:
          name: start mysql for tests
          command: |
            docker run --name bmo-mysql \
                       --network bmo_net \
                       --env-file=docker_files/tests.env \
                       --rm -d \
                       mozillabteam/bmo-mysql:5.6
      - run:
          name: start memcached for tests
          command: docker run --name bmo-memcached --network bmo_net -d memcached

      - run:
          name: populate mysql and data volume for tests
          command: |
            docker run --network bmo_net \
                       --env-file=docker_files/tests.env \
                       -v bmo_data:/app/data \
                       $BMO_IMAGE_NAME:$CIRCLE_BRANCH load_test_data
      - run:
          name: start httpd for testing web services
          command: |
            docker run --name bmo-web \
                       --network bmo_net \
                       --env-file=docker_files/tests.env \
                       -v bmo_data:/app/data \
                       -d \
                       $BMO_IMAGE_NAME:$CIRCLE_BRANCH httpd -DHTTPD_IN_SUBDIR
      - run:
          name: check heartbeat
          command: |
            docker run --network bmo_net \
                       --env-file=docker_files/tests.env \
                       -v bmo_data:/app/data \
                       $BMO_IMAGE_NAME:$CIRCLE_BRANCH test_heartbeat
      - run:
          name: test webservices
          command: |
            docker run --network bmo_net \
                       --env-file=docker_files/tests.env \
                       -v bmo_data:/app/data \
                       $BMO_IMAGE_NAME:$CIRCLE_BRANCH test_webservices
      - run:
          name: upload to dockerhub (if possible)
          command: |
            if [[ -n "$DOCKER_USER" && -n "$DOCKER_PASS" ]]; then
              docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
              docker push $BMO_IMAGE_NAME:$CIRCLE_BRANCH
            else
              echo "No DOCKER_USER/DOCKER_PASS, skipping docker push"
            fi
